[package]
name = "aoc2019"
version = "0.1.0"
authors = ["Dennis Hedegaard <dennis@dhedegaard.dk>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen="0.2"
permutohedron = "0.2.4"
regex = "1"
num-integer = "0.1.41"
