name: Build and deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag aoc2019
    - name: Extract the build
      run: mkdir ./output && docker run -i --rm -v `pwd`/output:/output aoc2019 sh -c "cp -rv /app/public/* /output"
    - run: echo "aoc2019.dhedegaard.dk" > ./output/CNAME
    - name: GitHub Pages
      uses: crazy-max/ghaction-github-pages@v1.2.5
      with:
        build_dir: ./output
      env:
        GITHUB_PAT: ${{ secrets.GH_PAT }}
