name: Deploy

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build and start the container
        run: docker build . --file Dockerfile --tag aoc2019 && docker run --rm --name aoc2019 aoc2019
      - name: Extract the build
        run: mkdir -p output &&  docker cp aoc2019:/usr/share/nginx/html/* ./output
      - run: find ./output
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.1.0
        with:
          build_dir: output
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
